[package]
name = "based_appchain_explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ether = { version = "0.11", package = "ethers"}
tokio = { version = "1", features = ["full"] }
cfg-if = "1.0"
